### ISSUE TITLE
Create user story map and finalise with clients

### ISSUE THREAD

**Issue by aidengeorge97** [cass-degrees/CASS-Degrees#1]

**Comment by spencerj411** [comment]
Ensure clients are content with it.

**Comment by JackSekoranja** [comment]
Completed and signed off with client.

User Story Map found here: https://docs.google.com/spreadsheets/d/1-JrDPFwQQ7a9Lt-Ci8eKgJC-9yZPuXGbhjtN30k2Yvk
Raw User Stories with Acceptance Criteria found here: https://docs.google.com/document/d/1nj0gj3BS6XL3B7XeQXr2or4Vxlh1Ah5AFw33DN0ZuBs
User Story Github Issues Here: https://github.com/cass-degrees/CASS-Degrees-Code/issues?q=is%3Aopen+is%3Aissue+label%3A%22User+Story%22
