### ISSUE TITLE
Send an Email to Amanda Snashnall about Intellidox

### ISSUE THREAD

**Issue by spencerj411** [cass-degrees/CASS-Degrees#21]
Amanda Snashnall (Director IDTC) contact details:
Email - amanda.snashall@anu.edu.au
Phone number - +61 2 6125 7159

**Comment by spencerj411** [comment]
Note: Ensure Amanda has enough time to reply back by PA2.

**Comment by JackSekoranja** [comment]
Decided to close the issue without initiating contact. The team feels there isn't much to be gained from contacting her this late in the project, although we will still keep her as a contact if needed in the future.
