### ISSUE TITLE
Develop wireframes to show the clients and gain feedback

### ISSUE THREAD

**Issue by spencerj411** [cass-degrees/CASS-Degrees#24]

**Comment by joshcbee** [comment]
Conversation starters discussed with client as part of workflow breakdown:
Wireframe 1: https://drive.google.com/open?id=1gARIftcUml_yYWUimJ1EoezU3b33z-CR
Wireframe 2: https://drive.google.com/open?id=17qZeSDnUdvaS4vQKO-moAeJaX2D_mQie

**Comment by j-selby** [comment]
Closing - wireframes have been sighted by client and approved. Notes were about minimizing clicking, as well as consistency with P&C.
