### ISSUE TITLE
Create a glossary of terms

### ISSUE THREAD

**Issue by aidengeorge97** [cass-degrees/CASS-Degrees#29]
See the week 5 client meeting about workflow for extra information

**Comment by j-selby** [comment]
Work in progress at https://docs.google.com/document/d/1I6ooU3A4Xb5QvDyWtfNf6tBaH99rFfVrf-RnzIBSb3I/edit

**Comment by j-selby** [comment]
Issue has been resolved - Glossary has been clarified with Client and filled out.
