### ISSUE TITLE
Move the Django Setup Guide to CASS-Degrees-Code

### ISSUE THREAD

**Issue by Daniel-Jang** [cass-degrees/CASS-Degrees#40]
Move this document as readme in the root directoroy of CASS-Degrees-Code: https://docs.google.com/document/d/1AP6ycdfm0Rk04vRhcsrh3G53PR-BPytMMqTyLkMv7vQ/

**Comment by KavsHub** [comment]
Will update this issue once the corresponding issue in the code repo has been closed

**Comment by KavsHub** [comment]
This has been done as the issue in the code repo has been closed.
