### ISSUE TITLE
Start Doing Research on PDF Generation using Django

### ISSUE THREAD

**Issue by spencerj411** [cass-degrees/CASS-Degrees#42]
*In Progress*
I've created a new 'Django PDF Generation' section in [Django Tutorials and Guides](https://docs.google.com/document/d/1FXCtVJEAUkPfoSmBiKUYZO2AcTY35uYEZmImrSnA-m4/edit#heading=h.mbipcbmlwjhq) (_Drive/CASS Degrees Techlauncher/Documentation/Technical Documentation/Django Documents/Django Tutorials and Guides_)

**Comment by j-selby** [comment]
Closing - see decision log.
