### ISSUE TITLE
Create Process Documents for UAT and Peer-To-Peer Code Review

### ISSUE THREAD

**Issue by spencerj411** [cass-degrees/CASS-Degrees#43]
We were advised by the tutors to write a formal process on our User Acceptance Testing/User Validation and how we review/approve each other's code on GitHub (rules must be documented too).

The advice was received from [Tutorial Meeting Week 7](https://docs.google.com/document/d/1Sjr2-8Xm0rOTkZHF8gDAo72I3L3fvIhJROyCRm1swDQ/edit).

**Comment by joshcbee** [comment]
Revised [Git Branching document](https://drive.google.com/open?id=1whU7j2F_0RFJ1n1rJsn3H6UcKvLCPCmKZ2J65a7D-9g) addresses peer-to-peer code review.

UAT Process outlined in [UAT Documents](https://drive.google.com/open?id=1M4ib70GMKbpx5FPBfZBrD0ULzidE1193RyyIoMnIu0o)
