### ISSUE TITLE
Ensure ALL Documentation in Google Drive and Landing Page are Updated

### ISSUE THREAD

**Issue by spencerj411** [cass-degrees/CASS-Degrees#44]
Reminded by the tutors during [Tutorial Meeting Week 7](https://docs.google.com/document/d/1Sjr2-8Xm0rOTkZHF8gDAo72I3L3fvIhJROyCRm1swDQ/edit).

Links:

- [Google Drive Root](https://drive.google.com/drive/u/1/folders/10U7-yYsQLGL0vKojnlN8gC1WB_mJcal7)

- [Landing Page](https://github.com/cass-degrees/CASS-Degrees)

**Comment by KavsHub** [comment]
Aiden will review Google Doc & I will review the landing page

**Comment by KavsHub** [comment]
This has been completed as of the most recent push (7/5/19)
