### ISSUE TITLE
Determine team roles

### ISSUE THREAD

**Issue by spencerj411** [cass-degrees/CASS-Degrees#8]

**Comment by joshcbee** [comment]
Draft Team Composition:
Aiden George 		(u6049100) - Database Manager
Daniel Jang 		(u6048122) - Web Framework Expert
Jack Sekoranja 	(u6049302) - Team Leader, Back end developer
James Lonie 		(u6379426) - Frontend, UX
Joshua Bee		(u4528333) - Assistant PM/BA/Client Liaison, UX
Kavan Lu 		(u6051623) - Full stack developer, UX Liason
Spencer Jimenez 	(u6051318) - Back end developer
